# Generated by Django 5.2.9 on 2025-12-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время синхронизации"
                    ),
                ),
                (
                    "added_count",
                    models.IntegerField(
                        default=0, verbose_name="Добавлено мероприятий"
                    ),
                ),
                (
                    "updated_count",
                    models.IntegerField(
                        default=0, verbose_name="Обновлено мероприятий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат синхронизации",
                "verbose_name_plural": "Результаты синхронизаций",
                "ordering": ["-sync_date"],
            },
        ),
    ]
