# Generated by Django 5.2.9 on 2025-12-21 15:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Площадка",
                "verbose_name_plural": "Площадки",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("event_time", models.DateTimeField(verbose_name="Дата проведения")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Открыто"), ("closed", "Закрыто")],
                        default="open",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.place",
                        verbose_name="Площадка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ("event_time",),
                "indexes": [
                    models.Index(
                        fields=["status", "event_time"],
                        name="events_even_status_93ee54_idx",
                    ),
                    models.Index(
                        fields=["event_time"], name="events_even_event_t_1c5c22_idx"
                    ),
                ],
            },
        ),
    ]
