# Generated by Django 5.2.9 on 2025-12-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_changed_at_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дедлайн регистрации"
            ),
        ),
    ]
