# Generated by Django 5.2.9 on 2025-12-24 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_notificationoutbox"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NotificationOutbox",
            new_name="OutboxMessage",
        ),
    ]
